import { Briefcase, Cake, Diamond, Music, PartyPopper, Tent } from "lucide-react";

export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
] as const;

export const EVENT_TYPES = [
  { id: "Wedding", label: "Wedding", icon: Diamond },
  { id: "Birthday", label: "Birthday", icon: Cake },
  { id: "Vendor", label: "Vendor at Event", icon: Briefcase },
  { id: "Corporate", label: "Corporate Event", icon: PartyPopper },
  { id: "Concert", label: "Concert / Festival", icon: Music },
  { id: "Other", label: "Other Event", icon: Tent },
] as const;

export const PLAN_OPTIONS = [
  {
    id: "basic",
    limit: "1 Million / 2 Million",
    accent: "bg-[#36a3dd] text-white",
    outline: "border-[#36a3dd] text-[#36a3dd]",
    price: "697",
    stats: [
      { label: "Per Occurence:", value: "$1 million" },
      { label: "Aggregate:", value: "$2 million" },
      { label: "Property Damage:", value: "$300,000" },
      { label: "Medical:", value: "$5,000" },
      { label: "Deductible:", value: "$0" },
    ],
  },
  {
    id: "standard",
    limit: "1 Million / 5 Million",
    accent: "bg-primary text-primary-foreground",
    outline: "border-primary text-primary-foreground bg-primary",
    price: "186",
    recommended: true,
    stats: [
      { label: "Per Occurence:", value: "$1 million" },
      { label: "Aggregate:", value: "$5 million" },
      { label: "Property Damage:", value: "$1 million" },
      { label: "Medical:", value: "$5,000" },
      { label: "Deductible:", value: "$0" },
    ],
  },
  {
    id: "premium",
    limit: "2 Million / 5 Million",
    accent: "bg-[#08a045] text-white",
    outline: "border-[#08a045] text-[#08a045]",
    price: "273",
    stats: [
      { label: "Per Occurence:", value: "$2 million" },
      { label: "Aggregate:", value: "$5 million" },
      { label: "Property Damage:", value: "$1 million" },
      { label: "Medical:", value: "$5,000" },
      { label: "Deductible:", value: "$0" },
    ],
  },
  {
    id: "enterprise",
    limit: "5 Million / 5 Million",
    accent: "bg-[#433d83] text-white",
    outline: "border-[#433d83] text-[#433d83]",
    price: "1244",
    stats: [
      { label: "Per Occurence:", value: "$5 million" },
      { label: "Aggregate:", value: "$5 million" },
      { label: "Property Damage:", value: "$1 million" },
      { label: "Medical:", value: "$5,000" },
      { label: "Deductible:", value: "$0" },
    ],
  },
] as const;

export const TOTAL_STEPS = 12;

export const primaryActionClass =
  "mx-auto flex min-w-[180px] items-center justify-center rounded-full px-10 py-4 text-base font-semibold transition-all duration-300";
